### PR TITLE
Added observability guide

### PR DESCRIPTION
**Pull request by klasahl**

### CODE REVIEW

**Review by mijanss — COMMENTED** [review]
Looks great.

I have only have one suggestion. Moving the links from the headers for MySQL and Redis to their own lines would make it more clear that they are links.

**Comment by klasahl** [comment]
Thanks for feedback. Moved the links to separate lines.

**Comment by klasahl** [comment]
Changed MSSQL port to 9399.

**Review by mijanss — APPROVED** [review]
LGTM

**Pull request merged**
